### ISSUE TITLE
gnuradio 3.7 core (not runtime)

### ISSUE THREAD

**Issue by cpbridges** [EdmundTse/gr-dvb#3]
Hi Ed,

Was wondering if you knew the correct flags or method to install gr-dvb from GR 3.7?

The configure gives me:
```
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.18... yes
checking for GNURADIO_CORE... configure: error: Package requirements (gnuradio-core >= 3) were not met:

No package 'gnuradio-core' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables GNURADIO_CORE_CFLAGS
and GNURADIO_CORE_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

odroid@odroid:~/gr-dvb$ 
```
73s Chris

**Comment by cpbridges** [comment]
Adding a fake gnuradio-core.pc that points to the runtime and this:
```
odroid@odroid:~/gr-dvb$ echo $GNURADIO_CORE_LIBS
/usr/lib/arm-linux-gnueabihf
```
Produces:
```
checking pkg-config is at least version 0.18... yes
checking for GNURADIO_CORE... yes
checking for GRUEL... configure: error: Package requirements (gruel >= 3) were not met:

No package 'gruel' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables GRUEL_CFLAGS
and GRUEL_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```
Getting closer. May have to convert all parts using gr_modtool. 73s C

**Comment by EdmundTse** [comment]
Hi Chris,

This codebase hasn't been touched for a while. I would suggest perhaps looking at one of the forks from this repository, where I recall there was a port over to the newer version of GNURadio with quite a lot of changes. See if you'll have better luck getting starting from there.

Edmund

**Comment by cpbridges** [comment]
Thanks @EdmundTse - I've found that @spiccinini's https://github.com/spiccinini/gr-dvb is ported but the typical cmake/make install does not give the same gnuradio companion blocks as the gr-dvb for @drmpeg's https://github.com/drmpeg/gr-dvbs examples. 

I'm hunting down all the settings now but thinking of running an older version to make what I had working, work again. 73s C

**Comment by cpbridges** [comment]
Nevermind, just found this:
https://kb.ettus.com/Transmitting_DVB-S2_with_GNU_Radio_and_an_USRP_B210

"As of GNU Radio 3.7.7, these modules have been merged into mainline GNU Radio under gr-dtv."

73s C

**Comment by drmpeg** [comment]
If you're interested in the receive portion of gr-dvb, you may find this useful.

http://www.pabr.org/radio/leandvb/leandvb.en.html

It's not targeted at GNU Radio, but it is current.
